name: Serve on custom domain

on:
  workflow_dispatch:
  push:
    paths:
      - './docs'

jobs:
  deploy_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
        
      - name: Copy CNAME in *docs* folder
        run: cp ./CNAME ./docs/CNAME

      - name: Commit changes
        run: |
          git config --global user.name 'GH Action'
          git config --global user.email 'the.kunitskyi@gmail.com'
          git commit -am "edit: copy CNAME in docs folder"
          git push
